use_frameworks!
def pod_list
  pod 'RNCryptor-objc'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'Pictograph' do
  platform :ios, '9.0'
  pod_list
  pod 'SVProgressHUD'
  pod 'EAIntroView'
  pod 'CustomIOSAlertView'
end

target 'Pictograph Mac' do
  platform :osx, '10.11'
  pod_list
end

target 'PictographTests' do

end

target 'PictographUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
